/**
 * Supabase Client for Devmart Marko
 * 
 * This client connects to our external Supabase project (not Lovable Cloud).
 * Environment variables are configured in .env:
 * - VITE_SUPABASE_URL
 * - VITE_SUPABASE_ANON_KEY
 * 
 * For production deployment (Hostinger VPS), these values must be set
 * in the production environment configuration.
 */

import { supabase } from '@/integrations/supabase/client';

// Re-export the supabase client for use throughout the app
export { supabase };

// Type exports (will be generated by Supabase CLI: npx supabase gen types typescript)
export type { Database } from '@/integrations/supabase/types';
