// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded values - anon key is public and safe to include in client-side code
const SUPABASE_URL = "https://ndaohonpvwvoadffwgst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYW9ob25wdnd2b2FkZmZ3Z3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MzUxOTQsImV4cCI6MjA4MDAxMTE5NH0.-Am1N7byz4aeyFCaJdz_nzDLnse8ZFGRPAFpoc7kbXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});